const conflictManagementMapping = (languageCode) => {
    const mappings = {
        en: {
            1: { A: 'Avoidance', B: 'Accommodation', C: 'Compromise', D: 'Collaboration', E: 'Competition' },
            2: { A: 'Accommodation', B: 'Competition', C: 'Compromise', D: 'Avoidance', E: 'Collaboration' },
            3: { A: 'Competition', B: 'Avoidance', C: 'Accommodation', D: 'Compromise', E: 'Collaboration' },
            4: { A: 'Competition', B: 'Collaboration', C: 'Avoidance', D: 'Accommodation', E: 'Compromise' },
            5: { A: 'Compromise', B: 'Competition', C: 'Avoidance', D: 'Accommodation', E: 'Collaboration' },
            6: { A: 'Accommodation', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Competition' },
            7: { A: 'Competition', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Accommodation' },
            8: { A: 'Competition', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Accommodation' },
            9: { A: 'Collaboration', B: 'Compromise', C: 'Competition', D: 'Avoidance', E: 'Accommodation' },
            10: { A: 'Compromise', B: 'Collaboration', C: 'Competition', D: 'Avoidance', E: 'Accommodation' },
            11: { A: 'Accommodation', B: 'Compromise', C: 'Avoidance', D: 'Competition', E: 'Collaboration' },
            12: { A: 'Accommodation', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Competition' },
            13: { A: 'Compromise', B: 'Accommodation', C: 'Competition', D: 'Collaboration', E: 'Avoidance' },
            14: { A: 'Competition', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Accommodation' },
            15: { A: 'Competition', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Accommodation' },
            16: { A: 'Accommodation', B: 'Compromise', C: 'Collaboration', D: 'Competition', E: 'Avoidance' },
            17: { A: 'Competition', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Accommodation' },
            18: { A: 'Competition', B: 'Compromise', C: 'Collaboration', D: 'Avoidance', E: 'Accommodation' },
            19: { A: 'Avoidance', B: 'Compromise', C: 'Collaboration', D: 'Competition', E: 'Accommodation' },
            20: { A: 'Compromise', B: 'Avoidance', C: 'Accommodation', D: 'Collaboration', E: 'Competition' },
            21: { A: 'Accommodation', B: 'Competition', C: 'Avoidance', D: 'Compromise', E: 'Collaboration' },
            22: { A: 'Accommodation', B: 'Collaboration', C: 'Competition', D: 'Avoidance', E: 'Compromise' },
            23: { A: 'Avoidance', B: 'Compromise', C: 'Collaboration', D: 'Accommodation', E: 'Competition' },
            24: { A: 'Accommodation', B: 'Avoidance', C: 'Compromise', D: 'Collaboration', E: 'Competition' },
            25: { A: 'Avoidance', B: 'Competition', C: 'Accommodation', D: 'Compromise', E: 'Collaboration' }
        },
        pt: {
            1: { A: 'Evasão', B: 'Acomodação', C: 'Compromisso', D: 'Colaboração', E: 'Competição' },
            2: { A: 'Acomodação', B: 'Competição', C: 'Compromisso', D: 'Evasão', E: 'Colaboração' },
            3: { A: 'Competição', B: 'Evasão', C: 'Acomodação', D: 'Compromisso', E: 'Colaboração' },
            4: { A: 'Competição', B: 'Colaboração', C: 'Evasão', D: 'Acomodação', E: 'Compromisso' },
            5: { A: 'Compromisso', B: 'Competição', C: 'Evasão', D: 'Acomodação', E: 'Colaboração' },
            6: { A: 'Acomodação', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Competição' },
            7: { A: 'Competição', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Acomodação' },
            8: { A: 'Competição', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Acomodação' },
            9: { A: 'Colaboração', B: 'Compromisso', C: 'Competição', D: 'Evasão', E: 'Acomodação' },
            10: { A: 'Compromisso', B: 'Colaboração', C: 'Competição', D: 'Evasão', E: 'Acomodação' },
            11: { A: 'Acomodação', B: 'Compromisso', C: 'Evasão', D: 'Competição', E: 'Colaboração' },
            12: { A: 'Acomodação', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Competição' },
            13: { A: 'Compromisso', B: 'Acomodação', C: 'Competição', D: 'Colaboração', E: 'Evasão' },
            14: { A: 'Competição', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Acomodação' },
            15: { A: 'Competição', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Acomodação' },
            16: { A: 'Acomodação', B: 'Compromisso', C: 'Colaboração', D: 'Competição', E: 'Evasão' },
            17: { A: 'Competição', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Acomodação' },
            18: { A: 'Competição', B: 'Compromisso', C: 'Colaboração', D: 'Evasão', E: 'Acomodação' },
            19: { A: 'Evasão', B: 'Compromisso', C: 'Colaboração', D: 'Competição', E: 'Acomodação' },
            20: { A: 'Compromisso', B: 'Evasão', C: 'Acomodação', D: 'Colaboração', E: 'Competição' },
            21: { A: 'Acomodação', B: 'Competição', C: 'Evasão', D: 'Compromisso', E: 'Colaboração' },
            22: { A: 'Acomodação', B: 'Colaboração', C: 'Competição', D: 'Evasão', E: 'Compromisso' },
            23: { A: 'Evasão', B: 'Compromisso', C: 'Colaboração', D: 'Acomodação', E: 'Competição' },
            24: { A: 'Acomodação', B: 'Evasão', C: 'Compromisso', D: 'Colaboração', E: 'Competição' },
            25: { A: 'Evasão', B: 'Competição', C: 'Acomodação', D: 'Compromisso', E: 'Colaboração' }
        },
        es: {
            1: { A: 'Evitación', B: 'Acomodación', C: 'Compromiso', D: 'Colaboración', E: 'Competencia' },
            2: { A: 'Acomodación', B: 'Competencia', C: 'Compromiso', D: 'Evitación', E: 'Colaboración' },
            3: { A: 'Competencia', B: 'Evitación', C: 'Acomodación', D: 'Compromiso', E: 'Colaboración' },
            4: { A: 'Competencia', B: 'Colaboración', C: 'Evitación', D: 'Acomodación', E: 'Compromiso' },
            5: { A: 'Compromiso', B: 'Competencia', C: 'Evitación', D: 'Acomodación', E: 'Colaboración' },
            6: { A: 'Acomodación', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Competencia' },
            7: { A: 'Competencia', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Acomodación' },
            8: { A: 'Competencia', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Acomodación' },
            9: { A: 'Colaboración', B: 'Compromiso', C: 'Competencia', D: 'Evitación', E: 'Acomodación' },
            10: { A: 'Compromiso', B: 'Colaboración', C: 'Competencia', D: 'Evitación', E: 'Acomodación' },
            11: { A: 'Acomodación', B: 'Compromiso', C: 'Evitación', D: 'Competencia', E: 'Colaboración' },
            12: { A: 'Acomodación', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Competencia' },
            13: { A: 'Compromiso', B: 'Acomodación', C: 'Competencia', D: 'Colaboración', E: 'Evitación' },
            14: { A: 'Competencia', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Acomodación' },
            15: { A: 'Competencia', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Acomodación' },
            16: { A: 'Acomodación', B: 'Compromiso', C: 'Colaboración', D: 'Competencia', E: 'Evitación' },
            17: { A: 'Competencia', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Acomodación' },
            18: { A: 'Competencia', B: 'Compromiso', C: 'Colaboración', D: 'Evitación', E: 'Acomodación' },
            19: { A: 'Evitación', B: 'Compromiso', C: 'Colaboración', D: 'Competencia', E: 'Acomodación' },
            20: { A: 'Compromiso', B: 'Evitación', C: 'Acomodación', D: 'Colaboración', E: 'Competencia' },
            21: { A: 'Acomodación', B: 'Competencia', C: 'Evitación', D: 'Compromiso', E: 'Colaboración' },
            22: { A: 'Acomodación', B: 'Colaboración', C: 'Competencia', D: 'Evitación', E: 'Compromiso' },
            23: { A: 'Evitación', B: 'Compromiso', C: 'Colaboración', D: 'Acomodación', E: 'Competencia' },
            24: { A: 'Acomodación', B: 'Evitación', C: 'Compromiso', D: 'Colaboración', E: 'Competencia' },
            25: { A: 'Evitación', B: 'Competencia', C: 'Acomodación', D: 'Compromiso', E: 'Colaboración' }
        },
        fr: {
            1: { A: 'Évitement', B: 'Accommodement', C: 'Compromis', D: 'Collaboration', E: 'Compétition' },
            2: { A: 'Accommodement', B: 'Compétition', C: 'Compromis', D: 'Évitement', E: 'Collaboration' },
            3: { A: 'Compétition', B: 'Évitement', C: 'Accommodement', D: 'Compromis', E: 'Collaboration' },
            4: { A: 'Compétition', B: 'Collaboration', C: 'Évitement', D: 'Accommodement', E: 'Compromis' },
            5: { A: 'Compromis', B: 'Compétition', C: 'Évitement', D: 'Accommodement', E: 'Collaboration' },
            6: { A: 'Accommodement', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Compétition' },
            7: { A: 'Compétition', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Accommodement' },
            8: { A: 'Compétition', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Accommodement' },
            9: { A: 'Collaboration', B: 'Compromis', C: 'Compétition', D: 'Évitement', E: 'Accommodement' },
            10: { A: 'Compromis', B: 'Collaboration', C: 'Compétition', D: 'Évitement', E: 'Accommodement' },
            11: { A: 'Accommodement', B: 'Compromis', C: 'Évitement', D: 'Compétition', E: 'Collaboration' },
            12: { A: 'Accommodement', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Compétition' },
            13: { A: 'Compromis', B: 'Accommodement', C: 'Compétition', D: 'Collaboration', E: 'Évitement' },
            14: { A: 'Compétition', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Accommodement' },
            15: { A: 'Compétition', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Accommodement' },
            16: { A: 'Accommodement', B: 'Compromis', C: 'Collaboration', D: 'Compétition', E: 'Évitement' },
            17: { A: 'Compétition', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Accommodement' },
            18: { A: 'Compétition', B: 'Compromis', C: 'Collaboration', D: 'Évitement', E: 'Accommodement' },
            19: { A: 'Évitement', B: 'Compromis', C: 'Collaboration', D: 'Compétition', E: 'Accommodement' },
            20: { A: 'Compromis', B: 'Évitement', C: 'Accommodement', D: 'Collaboration', E: 'Compétition' },
            21: { A: 'Accommodement', B: 'Compétition', C: 'Évitement', D: 'Compromis', E: 'Collaboration' },
            22: { A: 'Accommodement', B: 'Collaboration', C: 'Compétition', D: 'Évitement', E: 'Compromis' },
            23: { A: 'Évitement', B: 'Compromis', C: 'Collaboration', D: 'Accommodement', E: 'Compétition' },
            24: { A: 'Accommodement', B: 'Évitement', C: 'Compromis', D: 'Collaboration', E: 'Compétition' },
            25: { A: 'Évitement', B: 'Compétition', C: 'Accommodement', D: 'Compromis', E: 'Collaboration' }
        },
        ar: {
            1: { A: 'التجنب', B: 'التكيف', C: 'التسوية', D: 'التعاون', E: 'المنافسة' },
            2: { A: 'التكيف', B: 'المنافسة', C: 'التسوية', D: 'التجنب', E: 'التعاون' },
            3: { A: 'المنافسة', B: 'التجنب', C: 'التكيف', D: 'التسوية', E: 'التعاون' },
            4: { A: 'المنافسة', B: 'التعاون', C: 'التجنب', D: 'التكيف', E: 'التسوية' },
            5: { A: 'التسوية', B: 'المنافسة', C: 'التجنب', D: 'التكيف', E: 'التعاون' },
            6: { A: 'التكيف', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'المنافسة' },
            7: { A: 'المنافسة', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'التكيف' },
            8: { A: 'المنافسة', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'التكيف' },
            9: { A: 'التعاون', B: 'التسوية', C: 'المنافسة', D: 'التجنب', E: 'التكيف' },
            10: { A: 'التسوية', B: 'التعاون', C: 'المنافسة', D: 'التجنب', E: 'التكيف' },
            11: { A: 'التكيف', B: 'التسوية', C: 'التجنب', D: 'المنافسة', E: 'التعاون' },
            12: { A: 'التكيف', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'المنافسة' },
            13: { A: 'التسوية', B: 'التكيف', C: 'المنافسة', D: 'التعاون', E: 'التجنب' },
            14: { A: 'المنافسة', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'التكيف' },
            15: { A: 'المنافسة', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'التكيف' },
            16: { A: 'التكيف', B: 'التسوية', C: 'التعاون', D: 'المنافسة', E: 'التجنب' },
            17: { A: 'المنافسة', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'التكيف' },
            18: { A: 'المنافسة', B: 'التسوية', C: 'التعاون', D: 'التجنب', E: 'التكيف' },
            19: { A: 'التجنب', B: 'التسوية', C: 'التعاون', D: 'المنافسة', E: 'التكيف' },
            20: { A: 'التسوية', B: 'التجنب', C: 'التكيف', D: 'التعاون', E: 'المنافسة' },
            21: { A: 'التكيف', B: 'المنافسة', C: 'التجنب', D: 'التسوية', E: 'التعاون' },
            22: { A: 'التكيف', B: 'التعاون', C: 'المنافسة', D: 'التجنب', E: 'التسوية' },
            23: { A: 'التجنب', B: 'التسوية', C: 'التعاون', D: 'التكيف', E: 'المنافسة' },
            24: { A: 'التكيف', B: 'التجنب', C: 'التسوية', D: 'التعاون', E: 'المنافسة' },
            25: { A: 'التجنب', B: 'المنافسة', C: 'التكيف', D: 'التسوية', E: 'التعاون' }
        }
    };
    
    const selectedMapping = mappings[languageCode] || mappings['en']; // default to English if languageCode is not found
    console.log(`Loaded mapping for language ${languageCode}:`, selectedMapping);
    return selectedMapping;
    
};

module.exports = conflictManagementMapping;