// loveLanguageMapping.js

const loveLanguageMapping = (languageCode) => {
    const mappings = {
        en: {
            1: { A: 'Quality Time', B: 'Physical Touch', C: 'Words of Affirmation', D: 'Acts of Service', E: 'Receiving Gifts' },
            2: { A: 'Words of Affirmation', B: 'Receiving Gifts', C: 'Acts of Service', D: 'Physical Touch', E: 'Quality Time' },
            3: { A: 'Receiving Gifts', B: 'Quality Time', C: 'Physical Touch', D: 'Acts of Service', E: 'Words of Affirmation' },
            4: { A: 'Words of Affirmation', B: 'Physical Touch', C: 'Quality Time', D: 'Acts of Service', E: 'Receiving Gifts' },
            5: { A: 'Acts of Service', B: 'Words of Affirmation', C: 'Quality Time', D: 'Physical Touch', E: 'Receiving Gifts' },
            6: { A: 'Receiving Gifts', B: 'Physical Touch', C: 'Acts of Service', D: 'Quality Time', E: 'Words of Affirmation' },
            7: { A: 'Physical Touch', B: 'Quality Time', C: 'Words of Affirmation', D: 'Receiving Gifts', E: 'Acts of Service' },
            8: { A: 'Quality Time', B: 'Receiving Gifts', C: 'Physical Touch', D: 'Words of Affirmation', E: 'Acts of Service' },
            9: { A: 'Words of Affirmation', B: 'Receiving Gifts', C: 'Acts of Service', D: 'Physical Touch', E: 'Quality Time' },
            10: { A: 'Physical Touch', B: 'Receiving Gifts', C: 'Words of Affirmation', D: 'Acts of Service', E: 'Quality Time' },
            11: { A: 'Receiving Gifts', B: 'Quality Time', C: 'Physical Touch', D: 'Acts of Service', E: 'Words of Affirmation' },
            12: { A: 'Physical Touch', B: 'Receiving Gifts', C: 'Quality Time', D: 'Words of Affirmation', E: 'Acts of Service' },
            13: { A: 'Receiving Gifts', B: 'Words of Affirmation', C: 'Quality Time', D: 'Physical Touch', E: 'Acts of Service' },
            14: { A: 'Receiving Gifts', B: 'Quality Time', C: 'Acts of Service', D: 'Physical Touch', E: 'Words of Affirmation' },
            15: { A: 'Receiving Gifts', B: 'Quality Time', C: 'Physical Touch', D: 'Acts of Service', E: 'Words of Affirmation' },
            16: { A: 'Physical Touch', B: 'Receiving Gifts', C: 'Words of Affirmation', D: 'Quality Time', E: 'Acts of Service' },
            17: { A: 'Quality Time', B: 'Words of Affirmation', C: 'Receiving Gifts', D: 'Physical Touch', E: 'Acts of Service' },
            18: { A: 'Acts of Service', B: 'Receiving Gifts', C: 'Quality Time', D: 'Physical Touch', E: 'Words of Affirmation' },
            19: { A: 'Quality Time', B: 'Receiving Gifts', C: 'Physical Touch', D: 'Acts of Service', E: 'Words of Affirmation' },
            20: { A: 'Quality Time', B: 'Receiving Gifts', C: 'Physical Touch', D: 'Words of Affirmation', E: 'Acts of Service' },
            21: { A: 'Words of Affirmation', B: 'Receiving Gifts', C: 'Quality Time', D: 'Acts of Service', E: 'Physical Touch' },
            22: { A: 'Quality Time', B: 'Receiving Gifts', C: 'Physical Touch', D: 'Words of Affirmation', E: 'Acts of Service' },
            23: { A: 'Physical Touch', B: 'Words of Affirmation', C: 'Receiving Gifts', D: 'Quality Time', E: 'Acts of Service' },
            24: { A: 'Quality Time', B: 'Physical Touch', C: 'Receiving Gifts', D: 'Words of Affirmation', E: 'Acts of Service' },
            25: { A: 'Quality Time', B: 'Physical Touch', C: 'Receiving Gifts', D: 'Words of Affirmation', E: 'Acts of Service' }
        },
        es: {
            1: { A: 'Tiempo de Calidad', B: 'Toque Físico', C: 'Palabras de Afirmación', D: 'Actos de Servicio', E: 'Recibir Regalos' },
            2: { A: 'Palabras de Afirmación', B: 'Recibir Regalos', C: 'Actos de Servicio', D: 'Toque Físico', E: 'Tiempo de Calidad' },
            3: { A: 'Recibir Regalos', B: 'Tiempo de Calidad', C: 'Toque Físico', D: 'Actos de Servicio', E: 'Palabras de Afirmación' },
            4: { A: 'Palabras de Afirmación', B: 'Toque Físico', C: 'Tiempo de Calidad', D: 'Actos de Servicio', E: 'Recibir Regalos' },
            5: { A: 'Actos de Servicio', B: 'Palabras de Afirmación', C: 'Tiempo de Calidad', D: 'Toque Físico', E: 'Recibir Regalos' },
            6: { A: 'Recibir Regalos', B: 'Toque Físico', C: 'Actos de Servicio', D: 'Tiempo de Calidad', E: 'Palabras de Afirmación' },
            7: { A: 'Toque Físico', B: 'Tiempo de Calidad', C: 'Palabras de Afirmación', D: 'Recibir Regalos', E: 'Actos de Servicio' },
            8: { A: 'Tiempo de Calidad', B: 'Recibir Regalos', C: 'Toque Físico', D: 'Palabras de Afirmación', E: 'Actos de Servicio' },
            9: { A: 'Palabras de Afirmación', B: 'Recibir Regalos', C: 'Actos de Servicio', D: 'Toque Físico', E: 'Tiempo de Calidad' },
            10: { A: 'Toque Físico', B: 'Recibir Regalos', C: 'Palabras de Afirmación', D: 'Actos de Servicio', E: 'Tiempo de Calidad' },
            11: { A: 'Recibir Regalos', B: 'Tiempo de Calidad', C: 'Toque Físico', D: 'Actos de Servicio', E: 'Palabras de Afirmación' },
            12: { A: 'Toque Físico', B: 'Recibir Regalos', C: 'Tiempo de Calidad', D: 'Palabras de Afirmación', E: 'Actos de Servicio' },
            13: { A: 'Recibir Regalos', B: 'Palabras de Afirmación', C: 'Tiempo de Calidad', D: 'Toque Físico', E: 'Actos de Servicio' },
            14: { A: 'Recibir Regalos', B: 'Tiempo de Calidad', C: 'Actos de Servicio', D: 'Toque Físico', E: 'Palabras de Afirmación' },
            15: { A: 'Recibir Regalos', B: 'Tiempo de Calidad', C: 'Toque Físico', D: 'Actos de Servicio', E: 'Palabras de Afirmación' },
            16: { A: 'Toque Físico', B: 'Recibir Regalos', C: 'Palabras de Afirmación', D: 'Tiempo de Calidad', E: 'Actos de Servicio' },
            17: { A: 'Tiempo de Calidad', B: 'Palabras de Afirmación', C: 'Recibir Regalos', D: 'Toque Físico', E: 'Actos de Servicio' },
            18: { A: 'Actos de Servicio', B: 'Recibir Regalos', C: 'Tiempo de Calidad', D: 'Toque Físico', E: 'Palabras de Afirmación' },
            19: { A: 'Tiempo de Calidad', B: 'Recibir Regalos', C: 'Toque Físico', D: 'Actos de Servicio', E: 'Palabras de Afirmación' },
            20: { A: 'Tiempo de Calidad', B: 'Recibir Regalos', C: 'Toque Físico', D: 'Palabras de Afirmación', E: 'Actos de Servicio' },
            21: { A: 'Palabras de Afirmación', B: 'Recibir Regalos', C: 'Tiempo de Calidad', D: 'Actos de Servicio', E: 'Toque Físico' },
            22: { A: 'Tiempo de Calidad', B: 'Recibir Regalos', C: 'Toque Físico', D: 'Palabras de Afirmación', E: 'Actos de Servicio' },
            23: { A: 'Toque Físico', B: 'Palabras de Afirmación', C: 'Recibir Regalos', D: 'Tiempo de Calidad', E: 'Actos de Servicio' },
            24: { A: 'Tiempo de Calidad', B: 'Toque Físico', C: 'Recibir Regalos', D: 'Palabras de Afirmación', E: 'Actos de Servicio' },
            25: { A: 'Tiempo de Calidad', B: 'Toque Físico', C: 'Recibir Regalos', D: 'Palabras de Afirmación', E: 'Actos de Servicio' }
        },
        pt: {
            1: { A: 'Tempo de Qualidade', B: 'Toque Físico', C: 'Palavras de Afirmação', D: 'Atos de Serviço', E: 'Receber Presentes' },
            2: { A: 'Palavras de Afirmação', B: 'Receber Presentes', C: 'Atos de Serviço', D: 'Toque Físico', E: 'Tempo de Qualidade' },
            3: { A: 'Receber Presentes', B: 'Tempo de Qualidade', C: 'Toque Físico', D: 'Atos de Serviço', E: 'Palavras de Afirmação' },
            4: { A: 'Palavras de Afirmação', B: 'Toque Físico', C: 'Tempo de Qualidade', D: 'Atos de Serviço', E: 'Receber Presentes' },
            5: { A: 'Atos de Serviço', B: 'Palavras de Afirmação', C: 'Tempo de Qualidade', D: 'Toque Físico', E: 'Receber Presentes' },
            6: { A: 'Receber Presentes', B: 'Toque Físico', C: 'Atos de Serviço', D: 'Tempo de Qualidade', E: 'Palavras de Afirmação' },
            7: { A: 'Toque Físico', B: 'Tempo de Qualidade', C: 'Palavras de Afirmação', D: 'Receber Presentes', E: 'Atos de Serviço' },
            8: { A: 'Tempo de Qualidade', B: 'Receber Presentes', C: 'Toque Físico', D: 'Palavras de Afirmação', E: 'Atos de Serviço' },
            9: { A: 'Palavras de Afirmação', B: 'Receber Presentes', C: 'Atos de Serviço', D: 'Toque Físico', E: 'Tempo de Qualidade' },
            10: { A: 'Toque Físico', B: 'Receber Presentes', C: 'Palavras de Afirmação', D: 'Atos de Serviço', E: 'Tempo de Qualidade' },
            11: { A: 'Receber Presentes', B: 'Tempo de Qualidade', C: 'Toque Físico', D: 'Atos de Serviço', E: 'Palavras de Afirmação' },
            12: { A: 'Toque Físico', B: 'Receber Presentes', C: 'Tempo de Qualidade', D: 'Palavras de Afirmação', E: 'Atos de Serviço' },
            13: { A: 'Receber Presentes', B: 'Palavras de Afirmação', C: 'Tempo de Qualidade', D: 'Toque Físico', E: 'Atos de Serviço' },
            14: { A: 'Receber Presentes', B: 'Tempo de Qualidade', C: 'Atos de Serviço', D: 'Toque Físico', E: 'Palavras de Afirmação' },
            15: { A: 'Receber Presentes', B: 'Tempo de Qualidade', C: 'Toque Físico', D: 'Atos de Serviço', E: 'Palavras de Afirmação' },
            16: { A: 'Toque Físico', B: 'Receber Presentes', C: 'Palavras de Afirmação', D: 'Tempo de Qualidade', E: 'Atos de Serviço' },
            17: { A: 'Tempo de Qualidade', B: 'Palavras de Afirmação', C: 'Receber Presentes', D: 'Toque Físico', E: 'Atos de Serviço' },
            18: { A: 'Atos de Serviço', B: 'Receber Presentes', C: 'Tempo de Qualidade', D: 'Toque Físico', E: 'Palavras de Afirmação' },
            19: { A: 'Tempo de Qualidade', B: 'Receber Presentes', C: 'Toque Físico', D: 'Atos de Serviço', E: 'Palavras de Afirmação' },
            20: { A: 'Tempo de Qualidade', B: 'Receber Presentes', C: 'Toque Físico', D: 'Palavras de Afirmação', E: 'Atos de Serviço' },
            21: { A: 'Palavras de Afirmação', B: 'Receber Presentes', C: 'Tempo de Qualidade', D: 'Atos de Serviço', E: 'Toque Físico' },
            22: { A: 'Tempo de Qualidade', B: 'Receber Presentes', C: 'Toque Físico', D: 'Palavras de Afirmação', E: 'Atos de Serviço' },
            23: { A: 'Toque Físico', B: 'Palavras de Afirmação', C: 'Receber Presentes', D: 'Tempo de Qualidade', E: 'Atos de Serviço' },
            24: { A: 'Tempo de Qualidade', B: 'Toque Físico', C: 'Receber Presentes', D: 'Palavras de Afirmação', E: 'Atos de Serviço' },
            25: { A: 'Tempo de Qualidade', B: 'Toque Físico', C: 'Receber Presentes', D: 'Palavras de Afirmação', E: 'Atos de Serviço' }
        },
        fr: {
            1: { A: 'Temps de Qualité', B: 'Toucher Physique', C: 'Paroles d\'Affirmation', D: 'Actes de Service', E: 'Recevoir des Cadeaux' },
            2: { A: 'Paroles d\'Affirmation', B: 'Recevoir des Cadeaux', C: 'Actes de Service', D: 'Toucher Physique', E: 'Temps de Qualité' },
            3: { A: 'Recevoir des Cadeaux', B: 'Temps de Qualité', C: 'Toucher Physique', D: 'Actes de Service', E: 'Paroles d\'Affirmation' },
            4: { A: 'Paroles d\'Affirmation', B: 'Toucher Physique', C: 'Temps de Qualité', D: 'Actes de Service', E: 'Recevoir des Cadeaux' },
            5: { A: 'Actes de Service', B: 'Paroles d\'Affirmation', C: 'Temps de Qualité', D: 'Toucher Physique', E: 'Recevoir des Cadeaux' },
            6: { A: 'Recevoir des Cadeaux', B: 'Toucher Physique', C: 'Actes de Service', D: 'Temps de Qualité', E: 'Paroles d\'Affirmation' },
            7: { A: 'Toucher Physique', B: 'Temps de Qualité', C: 'Paroles d\'Affirmation', D: 'Recevoir des Cadeaux', E: 'Actes de Service' },
            8: { A: 'Temps de Qualité', B: 'Recevoir des Cadeaux', C: 'Toucher Physique', D: 'Paroles d\'Affirmation', E: 'Actes de Service' },
            9: { A: 'Paroles d\'Affirmation', B: 'Recevoir des Cadeaux', C: 'Actes de Service', D: 'Toucher Physique', E: 'Temps de Qualité' },
            10: { A: 'Toucher Physique', B: 'Recevoir des Cadeaux', C: 'Paroles d\'Affirmation', D: 'Actes de Service', E: 'Temps de Qualité' },
            11: { A: 'Recevoir des Cadeaux', B: 'Temps de Qualité', C: 'Toucher Physique', D: 'Actes de Service', E: 'Paroles d\'Affirmation' },
            12: { A: 'Toucher Physique', B: 'Recevoir des Cadeaux', C: 'Temps de Qualité', D: 'Paroles d\'Affirmation', E: 'Actes de Service' },
            13: { A: 'Recevoir des Cadeaux', B: 'Paroles d\'Affirmation', C: 'Temps de Qualité', D: 'Toucher Physique', E: 'Actes de Service' },
            14: { A: 'Recevoir des Cadeaux', B: 'Temps de Qualité', C: 'Actes de Service', D: 'Toucher Physique', E: 'Paroles d\'Affirmation' },
            15: { A: 'Recevoir des Cadeaux', B: 'Temps de Qualité', C: 'Toucher Physique', D: 'Actes de Service', E: 'Paroles d\'Affirmation' },
            16: { A: 'Toucher Physique', B: 'Recevoir des Cadeaux', C: 'Paroles d\'Affirmation', D: 'Temps de Qualité', E: 'Actes de Service' },
            17: { A: 'Temps de Qualité', B: 'Paroles d\'Affirmation', C: 'Recevoir des Cadeaux', D: 'Toucher Physique', E: 'Actes de Service' },
            18: { A: 'Actes de Service', B: 'Recevoir des Cadeaux', C: 'Temps de Qualité', D: 'Toucher Physique', E: 'Paroles d\'Affirmation' },
            19: { A: 'Temps de Qualité', B: 'Recevoir des Cadeaux', C: 'Toucher Physique', D: 'Actes de Service', E: 'Paroles d\'Affirmation' },
            20: { A: 'Temps de Qualité', B: 'Recevoir des Cadeaux', C: 'Toucher Physique', D: 'Paroles d\'Affirmation', E: 'Actes de Service' },
            21: { A: 'Paroles d\'Affirmation', B: 'Recevoir des Cadeaux', C: 'Temps de Qualité', D: 'Actes de Service', E: 'Toucher Physique' },
            22: { A: 'Temps de Qualité', B: 'Recevoir des Cadeaux', C: 'Toucher Physique', D: 'Paroles d\'Affirmation', E: 'Actes de Service' },
            23: { A: 'Toucher Physique', B: 'Paroles d\'Affirmation', C: 'Recevoir des Cadeaux', D: 'Temps de Qualité', E: 'Actes de Service' },
            24: { A: 'Temps de Qualité', B: 'Toucher Physique', C: 'Recevoir des Cadeaux', D: 'Paroles d\'Affirmation', E: 'Actes de Service' },
            25: { A: 'Temps de Qualité', B: 'Toucher Physique', C: 'Recevoir des Cadeaux', D: 'Paroles d\'Affirmation', E: 'Actes de Service' }
        },
        ar: {
            1: { A: 'وقت ممتع', B: 'اللمس الجسدي', C: 'كلمات التأكيد', D: 'أفعال الخدمة', E: 'تلقي الهدايا' },
            2: { A: 'كلمات التأكيد', B: 'تلقي الهدايا', C: 'أفعال الخدمة', D: 'اللمس الجسدي', E: 'وقت ممتع' },
            3: { A: 'تلقي الهدايا', B: 'وقت ممتع', C: 'اللمس الجسدي', D: 'أفعال الخدمة', E: 'كلمات التأكيد' },
            4: { A: 'كلمات التأكيد', B: 'اللمس الجسدي', C: 'وقت ممتع', D: 'أفعال الخدمة', E: 'تلقي الهدايا' },
            5: { A: 'أفعال الخدمة', B: 'كلمات التأكيد', C: 'وقت ممتع', D: 'اللمس الجسدي', E: 'تلقي الهدايا' },
            6: { A: 'تلقي الهدايا', B: 'اللمس الجسدي', C: 'أفعال الخدمة', D: 'وقت ممتع', E: 'كلمات التأكيد' },
            7: { A: 'اللمس الجسدي', B: 'وقت ممتع', C: 'كلمات التأكيد', D: 'تلقي الهدايا', E: 'أفعال الخدمة' },
            8: { A: 'وقت ممتع', B: 'تلقي الهدايا', C: 'اللمس الجسدي', D: 'كلمات التأكيد', E: 'أفعال الخدمة' },
            9: { A: 'كلمات التأكيد', B: 'تلقي الهدايا', C: 'أفعال الخدمة', D: 'اللمس الجسدي', E: 'وقت ممتع' },
            10: { A: 'اللمس الجسدي', B: 'تلقي الهدايا', C: 'كلمات التأكيد', D: 'أفعال الخدمة', E: 'وقت ممتع' },
            11: { A: 'تلقي الهدايا', B: 'وقت ممتع', C: 'اللمس الجسدي', D: 'أفعال الخدمة', E: 'كلمات التأكيد' },
            12: { A: 'اللمس الجسدي', B: 'تلقي الهدايا', C: 'وقت ممتع', D: 'كلمات التأكيد', E: 'أفعال الخدمة' },
            13: { A: 'تلقي الهدايا', B: 'كلمات التأكيد', C: 'وقت ممتع', D: 'اللمس الجسدي', E: 'أفعال الخدمة' },
            14: { A: 'تلقي الهدايا', B: 'وقت ممتع', C: 'أفعال الخدمة', D: 'اللمس الجسدي', E: 'كلمات التأكيد' },
            15: { A: 'تلقي الهدايا', B: 'وقت ممتع', C: 'اللمس الجسدي', D: 'أفعال الخدمة', E: 'كلمات التأكيد' },
            16: { A: 'اللمس الجسدي', B: 'تلقي الهدايا', C: 'كلمات التأكيد', D: 'وقت ممتع', E: 'أفعال الخدمة' },
            17: { A: 'وقت ممتع', B: 'كلمات التأكيد', C: 'تلقي الهدايا', D: 'اللمس الجسدي', E: 'أفعال الخدمة' },
            18: { A: 'أفعال الخدمة', B: 'تلقي الهدايا', C: 'وقت ممتع', D: 'اللمس الجسدي', E: 'كلمات التأكيد' },
            19: { A: 'وقت ممتع', B: 'تلقي الهدايا', C: 'اللمس الجسدي', D: 'أفعال الخدمة', E: 'كلمات التأكيد' },
            20: { A: 'وقت ممتع', B: 'تلقي الهدايا', C: 'اللمس الجسدي', D: 'كلمات التأكيد', E: 'أفعال الخدمة' },
            21: { A: 'كلمات التأكيد', B: 'تلقي الهدايا', C: 'وقت ممتع', D: 'أفعال الخدمة', E: 'اللمس الجسدي' },
            22: { A: 'وقت ممتع', B: 'تلقي الهدايا', C: 'اللمس الجسدي', D: 'كلمات التأكيد', E: 'أفعال الخدمة' },
            23: { A: 'اللمس الجسدي', B: 'كلمات التأكيد', C: 'تلقي الهدايا', D: 'وقت ممتع', E: 'أفعال الخدمة' },
            24: { A: 'وقت ممتع', B: 'اللمس الجسدي', C: 'تلقي الهدايا', D: 'كلمات التأكيد', E: 'أفعال الخدمة' },
            25: { A: 'وقت ممتع', B: 'اللمس الجسدي', C: 'تلقي الهدايا', D: 'كلمات التأكيد', E: 'أفعال الخدمة' }
        }
    };

    return mappings[languageCode] || mappings['en']; // default to English if languageCode is not found
};

module.exports = loveLanguageMapping; // This makes the mapping accessible in other files